# SOPS configuration file
# Using Azure Key Vault for encryption/decryption

creation_rules:
  # Rule for all YAML files including values-minimal.yaml
  - path_regex: \.yaml$
    azure_keyvault: 'https://inpro.vault.azure.net/keys/sops-shared/ef90dcdfcd0e47489cd0833d3ccff11b'
