apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  configManagementPlugins: |
    - name: sops-vault
      generate:
        command: ["sh", "-c"]
        args:
          - |
            export VAULT_ADDR=http://vault.default.svc.cluster.local:8200
            export VAULT_TOKEN=$(cat /var/run/secrets/vault/token)
            sops -d *.yaml | kubectl apply -f -
