apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: sops-vault
    spec:
      version: v1.0
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' -exec grep -l 'sops:' {} \\;"
      generate:
        command:
          - sh
          - "-c"
          - |
            for file in $(find . -name '*.yaml'); do
              if grep -q "sops:" "$file" 2>/dev/null; then
                # Replace 127.0.0.1 with cluster address in SOPS metadata during decryption
                sed 's|http://127.0.0.1:8200|http://vault.default.svc.cluster.local:8200|g' "$file" | sops -d /dev/stdin
              else
                cat "$file"
              fi
            done
