apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "argocd"
        vault.hashicorp.com/agent-inject-secret-token: "auth/kubernetes/login"
        vault.hashicorp.com/agent-inject-file-token: "token"
    spec:
      serviceAccountName: argocd-repo-server
      containers:
      - name: argocd-repo-server
        image: argoproj/argocd:latest
        env:
        - name: VAULT_ADDR
          value: "http://vault.default.svc.cluster.local:8200"
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/vault
          readOnly: true
      volumes:
      - name: vault-token
        emptyDir: {}
