apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmp-sops
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: sops
    spec:
      version: v1.0
      init:
        command: [sh, -c]
        args: ["echo 'Initializing SOPS plugin'"]
      generate:
        command: [sh, -c]
        args: ["sops -d *.enc.yaml"]
      discover:
        fileName: "*.enc.yaml"
