apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: sops
    spec:
      version: v1.0
      generate:
        command: ["sh", "-c"]
        args:
          - |
            for f in $(find . -name '*.yaml'); do
              sops -d "$f" 2>/dev/null || cat "$f"
              echo '---'
            done
