apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: backend
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:NI7n7c4=,iv:buLHuApzGpH219+GVNN8truPlo6qi5+XA0xGM+pkWlM=,tag:fuGEUauzWlFk92o43k2A8Q==,type:str]
    password: ENC[AES256_GCM,data:P1D8bObv,iv:OoTnmOkRuz6O9SxJH3cBkbFqTKy1FyXaEI9PnJjwUA8=,tag:3dAkhDkNczzs9vHbfLWPRQ==,type:int]
sops:
    age:
        - recipient: age159k5u8ceh5xhz2e4tucnfjrn2adz9prllk7c5peg9kmuj8j0uavsenqzc0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWWtNY1phUlUrUzc4dy9I
            L01td2V4MFFjNllSSXJhV083V2tITHhET1g0CnAwcWpFYy9Za001K1oyWTV3YTIr
            YUtWL2M1Qys2VXVSOXdKUklrU0QvUGMKLS0tIGEvbVk0OFBZYXJzZzlEL0VEUUgz
            dDFPbUo5OGZMcm5PRmdSV2pMbGRHaGMKeuEFbEewvmBFf3qLJMiGJxwTH4ZiVWIU
            ZS/Pyqba0TexBqYmG73yg4eX1e3VIvhFn5Uh4SzX2YTUVurRzt5y9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T13:45:14Z"
    mac: ENC[AES256_GCM,data:z6q3uHu693r/BVb8H41F5nA1q2iRVxd9YpNaCCTMUVpsEMrCMInYhtTo+Xz5oMjHNTyUD4UXRGqhJuf/uczar1h8jZsUlT4HYZz3sh9g6QOBFLf4ovA5eB6kZvH/ocfXNiYJlXTrURYKSaGc+JoHsl+syGnkGNHV7bqt5DjvX8A=,iv:2n8W533AWcrz1Kj6ppocVByLZ9vydAzrsVaNhWpEREQ=,tag:sEs61sQpZvgrTZvxxc4qNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
