apiVersion: v1
kind: Secret
metadata:
    name: app-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:tfhcSMA=,iv:BzmCXSS+M/a/uILU4mskRqynpLgy/2dYlJD2QxxljBk=,tag:PNVgR++Lxr2L2ce8ciifNA==,type:str]
    password: ENC[AES256_GCM,data:7KfuVkfy+DIZaXbAD9lLUdMeZe3dYg==,iv:5Q8xoQ3NWpJw3ob+sVaH43LhHwYs24EoPq+TBTzQORw=,tag:XySHpKLt9ew/030PksWcyg==,type:str]
sops:
    hc_vault:
        - vault_address: http://127.0.0.1:8200
          engine_path: transit
          key_name: sops-key
          created_at: "2025-12-01T10:38:06Z"
          enc: vault:v1:6WY43PLyC2Y7DxV+U40csB07mzi2xu5akqR9QCUDELIfVKM4736rOqnfXq5foupidFu2UYaOODxRoeS9
    lastmodified: "2025-12-01T10:38:06Z"
    mac: ENC[AES256_GCM,data:Dy+49pjc5UYerTXgXaPEu1xr2A2URK6re8dbPYgL2MV8Z0o7TcXfgyOpBG0mJ1NBiRdXniQQpMwqDyG76I5sVcFVcQR2IgIuaZ8hQpJJipcMvjEWuEShlraLib0tBiWViDUYr/mmW3H82CxJDsH49HEYJGrp1MDlpWvabk15D8U=,iv:RrF4sDfLulMoX5frQbBBseRLizxIrn/92i7vIenAsMQ=,tag:RDrnoEUVW8/ZyzlFfliKXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
