apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/FaresMirza/test-vault.git"
    path: .
    targetRevision: main
    plugin:
      name: sops-v1.0
      env:
        - name: SOPS_AGE_KEY_FILE
          value: /deploy/age.agekey
  destination:
    namespace: backend
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
